AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  BBS

  Sample SAM Template for bbs

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DYNAMO_ENDPOINT: DYNAMO_ENDPOINT
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  GetAllBBSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_all_bbs/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        get_all_bbs:
          Type: Api
          Properties:
            Path: /bbs/
            Method: get
            
  GetIdBBSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_id_bbs/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        get_id_bbs:
          Type: Api
          Properties:
            Path: /bbsid/
            Method: get

  RegisterBBSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: register_bbs/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        register_bbs:
          Type: Api
          Properties:
            Path: /register/
            Method: post

  DeleteBBSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_bbs/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        delete_bbs:
          Type: Api
          Properties:
            Path: /delete/
            Method: post

Outputs:
  GetAllBBSApi:
    Description: "API Gateway endpoint URL for Prod stage for Get All BBS function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bbs/"
  GetAllBBSFunction:
    Description: "Get All BBS Lambda Function ARN"
    Value: !GetAtt GetAllBBSFunction.Arn
  GetAllBBSIamRole:
    Description: "Implicit IAM Role created for Get All BBS function"
    Value: !GetAtt GetAllBBSFunctionRole.Arn

  GetIdBBSApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Id BBS function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bbsid/"
  GetIdBBSFunction:
    Description: "Get Id BBS Lambda Function ARN"
    Value: !GetAtt GetIDBBSFunction.Arn
  GetIdBBSIamRole:
    Description: "Implicit IAM Role created for Get Id BBS function"
    Value: !GetAtt GetIDBBSFunctionRole.Arn

  RegisterBBSApi:
    Description: "API Gateway endpoint URL for Prod stage for Register BBS function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register/"
  RegisterBBSFunction:
    Description: "Register BBS Lambda Function ARN"
    Value: !GetAtt RegisterBBSFunction.Arn
  RegisterBBSIamRole:
    Description: "Implicit IAM Role created for Register BBS function"
    Value: !GetAtt RegisterBBSFunctionRole.Arn

  DeleteBBSApi:
    Description: "API Gateway endpoint URL for Prod stage for Register BBS function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete/"
  DeleteBBSFunction:
    Description: "Delete BBS Lambda Function ARN"
    Value: !GetAtt DeleteBBSFunction.Arn
  DeleteBBSIamRole:
    Description: "Implicit IAM Role created for Register BBS function"
    Value: !GetAtt DeleteBBSFunctionRole.Arn
